const valorant = require("../Bussines/valorant");
var express = require('express');
var router = express.Router();

var leaderBoard={
  "actId":"d929bc38-4ab6-7da4-94f0-ee84f8ac141e",
  "players":[
     {
        "puuid":"MhMveeiYP8bbPzLEowVlKNJ-Q5-7K15LDn10SvyTCiXAc_eF0BRGqQ9WjFrIP_zGyjH8R6suCUur8Q",
        "gameName":"LOS prince",
        "tagLine":"ntc",
        "leaderboardRank":1,
        "rankedRating":1036,
        "numberOfWins":62,
        "competitiveTier":24
     },
     {
        "puuid":"h4kZr_L4f6E4hVm2NeSTBlMBmJESQK3D2xHxvfABsmcgx-XxzRJFNsA3srykrLb32bDbYTXGYW6gJg",
        "gameName":"LOUD sacy",
        "tagLine":"LLL",
        "leaderboardRank":2,
        "rankedRating":1021,
        "numberOfWins":63,
        "competitiveTier":24
     },
     {
        "puuid":"TCeKyljSAbMSPIPb7obsOXDrdJoirMgQZjmZLCnHl6r4JKyQioO_QZgYObFTVs1vtceQWvcAup1wRQ",
        "gameName":"HTR",
        "tagLine":"HaTeR",
        "leaderboardRank":3,
        "rankedRating":1001,
        "numberOfWins":119,
        "competitiveTier":24
     },
     {
        "puuid":"V8Z3MUUv6NS5TrnHFuLvlNfMTS4MUhyiGMWasVKNgIugAGnuexR4zaXNY7nU3ofjbAag4_lQwlooLw",
        "gameName":"LOUD aspas",
        "tagLine":"LLL",
        "leaderboardRank":4,
        "rankedRating":985,
        "numberOfWins":66,
        "competitiveTier":24
     },
     {
        "puuid":"JyVlam0B4i2ebMcyaVMqJs3ofmq3iRwqaW57dZl8YUkQnUgeN89GNrgqjUcVNti8c1TbRK89ETR7eg",
        "gameName":"LIBERTY shion",
        "tagLine":"0000",
        "leaderboardRank":5,
        "rankedRating":982,
        "numberOfWins":67,
        "competitiveTier":24
     },
     {
        "puuid":"__dhvSGu2Jnx8o7KIpotg-wTy-aLgCXC5BrLYqLf_dlb4iP_ts4jKQul4vu-rvI9_d1qj2b3NgIX3A",
        "gameName":"artzin",
        "tagLine":"fahid",
        "leaderboardRank":6,
        "rankedRating":977,
        "numberOfWins":98,
        "competitiveTier":24
     },
     {
        "puuid":"P-eWUymRDwVcnqzPrQ9kmSJsp3aNb-L-vfzSzB7mrukzeXUPIuv55RD_wUuQhXjoSFJ4qOjD7Oufxg",
        "gameName":"LOUD Less",
        "tagLine":"LLL",
        "leaderboardRank":7,
        "rankedRating":962,
        "numberOfWins":64,
        "competitiveTier":24
     },
     {
        "puuid":"eJq1NSxckrpH4ebJPnTerQImJN2BWlCnN4wT-BMBrynBjietQTjye35EDtqaxWgu5yO3s-gyrXfBGw",
        "gameName":"MIBR jzz",
        "tagLine":"luu",
        "leaderboardRank":8,
        "rankedRating":949,
        "numberOfWins":83,
        "competitiveTier":24
     },
     {
        "puuid":"HYpy6SUywdccRlSZC4dTnGp0H2k54k1nLpn67GmjT29aAtiUpp1VT-ioeJ90Yw0czOUx1ZoczYAsig",
        "gameName":"TBK tuyZ",
        "tagLine":"2003",
        "leaderboardRank":9,
        "rankedRating":930,
        "numberOfWins":99,
        "competitiveTier":24
     },
     {
        "puuid":"htMLCglVQYohaUEJCwpv2VxQXbQLc7dD7t6eSV4hoi6td1PugAUAci9Co4TyE2SQlWTRoh2BJpAk7A",
        "gameName":"LOS RND",
        "tagLine":"japz",
        "leaderboardRank":10,
        "rankedRating":919,
        "numberOfWins":101,
        "competitiveTier":24
     },
     {
        "puuid":"UxqXazlovBuLPPrBwVNmSRiTdNAS-WdpbuBm2wpaJil7ONiG4C5YfOFEtquKqT_FhdAc3Fkq9U0uGQ",
        "gameName":"LOS CTC",
        "tagLine":"caio",
        "leaderboardRank":11,
        "rankedRating":902,
        "numberOfWins":62,
        "competitiveTier":24
     },
     {
        "puuid":"YpbHiLnvmsQUDcCKF57RWBV2tC906EYaIBYsdvhEgBsBG_I3HBsSo6VVrppLHcaabpjFx_TdnhVFGw",
        "gameName":"anao sp1ke",
        "tagLine":"2007",
        "leaderboardRank":12,
        "rankedRating":894,
        "numberOfWins":138,
        "competitiveTier":24
     },
     {
        "puuid":"fcXm7ZIhsT9o-XHx2n5ezmR3kSpH1Iha5RZh-peACdIHc1aIj2-7r6R2YwKE4gWwouZF9l8fa38Dng",
        "gameName":"MIBR mNdS",
        "tagLine":"1109",
        "leaderboardRank":13,
        "rankedRating":889,
        "numberOfWins":85,
        "competitiveTier":24
     },
     {
        "puuid":"HQB-hbmaXPkZ-AQHBuEcXWcvE9Kp2mpjQOHTFP2CA7IK0YT5xrQXfobZn7V68VXHvkt6SxJg0faqzA",
        "gameName":"zaninZS",
        "tagLine":"zan",
        "leaderboardRank":14,
        "rankedRating":885,
        "numberOfWins":106,
        "competitiveTier":24
     },
     {
        "puuid":"gLZ9bNtX__660IL5YGmoPPTPWHDY3QdJr6JZQAVqVa4XdOiU7zWYOtIv6xAovVu9HkmFf1nT4I25rA",
        "gameName":"GuhRVN",
        "tagLine":"dani",
        "leaderboardRank":15,
        "rankedRating":883,
        "numberOfWins":68,
        "competitiveTier":24
     },
     {
        "puuid":"AkPIy7I9IIR0DaNyalPWTh87ysblfEPtWAo0nZpht3vZDIPeZOnsYK_20WO0nt1yFQtEI2s3BT3T4w",
        "gameName":"FUR Khalil",
        "tagLine":"bst",
        "leaderboardRank":16,
        "rankedRating":878,
        "numberOfWins":66,
        "competitiveTier":24
     },
     {
        "puuid":"FTPUK9Ikq8Qqa8g8xsRxQomKhuWIQx9a0kNxRmzNS_9MahmqT71_rtmcb5EDakNORRbsTPOHJ48LQA",
        "gameName":"LOUD Saadhak",
        "tagLine":"LLL",
        "leaderboardRank":17,
        "rankedRating":854,
        "numberOfWins":42,
        "competitiveTier":24
     },
     {
        "puuid":"THKTYQ608cRq1BuVbZhK9owvn_w33Wcxh4gRae8N58zm64irbKwJMbt1yDqRqkpgF5FyWSJzq8YaJQ",
        "gameName":"GL esahcSSJ",
        "tagLine":"777",
        "leaderboardRank":18,
        "rankedRating":847,
        "numberOfWins":55,
        "competitiveTier":24
     },
     {
        "puuid":"M-vs0R7tXKWB06Y_NGIGLOqCZa-fUncmgtT-roZ1T3ce-O22z53OTcoRxOe8kjVTodMnD0zQjwQGLA",
        "gameName":"guintt",
        "tagLine":"0001",
        "leaderboardRank":19,
        "rankedRating":847,
        "numberOfWins":139,
        "competitiveTier":24
     },
     {
        "puuid":"vjZ6nKpq4UZN8JSsCedSSxOOk3GpyiGn0k9MkIYkkytS94Gn8LuGfS2Lc_hiK9ozcEszC48qRr81cA",
        "gameName":"FUR mzn",
        "tagLine":"2wc",
        "leaderboardRank":20,
        "rankedRating":847,
        "numberOfWins":73,
        "competitiveTier":24
     },
     {
        "puuid":"5oKbw0YvXSNYnwpPA5jexMyHS8lYUjVPZ9n04yf7xdjxuiTfP2yK8cuH4ryRg-VV96gk8_T5C_Gdqw",
        "gameName":"Brinkss3",
        "tagLine":"2000",
        "leaderboardRank":21,
        "rankedRating":826,
        "numberOfWins":59,
        "competitiveTier":24
     },
     {
        "puuid":"njiMUihmyX0N6pNG3KG-B-DuCwf4xQwjeTbCpwVoORLGPkgPMEvSW3mQH5dWfX0aQgXinh2UFu0gPQ",
        "gameName":"leoziN",
        "tagLine":"2006",
        "leaderboardRank":22,
        "rankedRating":824,
        "numberOfWins":137,
        "competitiveTier":24
     },
     {
        "puuid":"BO6nxXWYEEBiY-w07e8qJOI6Ng-Q3FaNrUsxhJWrOqfdtFElq1Krlyi4EQ7xbekciarsQMz81HhKcw",
        "gameName":"MIBR denaro",
        "tagLine":"1104",
        "leaderboardRank":23,
        "rankedRating":822,
        "numberOfWins":60,
        "competitiveTier":24
     },
     {
        "puuid":"G4KxQvjeHYZzHugPkVCIeFjW26_F1sccn-tLa_42_YVwU6b0sSOYPFo0xW6NHBvVcRiUf-QcVDE-fA",
        "gameName":"Siduzord",
        "tagLine":"spot",
        "leaderboardRank":24,
        "rankedRating":820,
        "numberOfWins":90,
        "competitiveTier":24
     },
     {
        "leaderboardRank":25,
        "rankedRating":809,
        "numberOfWins":126,
        "competitiveTier":24
     },
     {
        "puuid":"WiPMILA7aDs7iaWEeHHsWyIcqAzID62AdK5XgenARiY8WxMA_nF5m2JNZOLe4m-eLvSPIWcvP68pfQ",
        "gameName":"l4cerBRG",
        "tagLine":"3006",
        "leaderboardRank":26,
        "rankedRating":800,
        "numberOfWins":50,
        "competitiveTier":24
     },
     {
        "puuid":"hI-ARxUsm6EjcO3Ot3UdmdFVpZRO7bUN9Mm3IDyDzyonsFQjD5qjtvVLnl2n-JoQdHkbeyeK0cAZVw",
        "gameName":"xicreti",
        "tagLine":"SACAO",
        "leaderboardRank":27,
        "rankedRating":794,
        "numberOfWins":83,
        "competitiveTier":24
     },
     {
        "puuid":"V88mOxR_csULh0SV4dlSYWhekSBvlVeuC-xRCC5g_oEFPvjtOl4F1sNHmVRfW3pIsPplP1Kc6iosdg",
        "gameName":"GL DGSY22KO",
        "tagLine":"2WCP",
        "leaderboardRank":28,
        "rankedRating":793,
        "numberOfWins":124,
        "competitiveTier":24
     },
     {
        "puuid":"wUHTayYN9nOGiHlIQgTAnWzc1ztZ_0AX9IglDuUHkJIUGwfdvPtFWMKrociFK6pWM5krD0h5HwgJyA",
        "gameName":"NIP cauanzin",
        "tagLine":"ninja",
        "leaderboardRank":29,
        "rankedRating":792,
        "numberOfWins":42,
        "competitiveTier":24
     },
     {
        "puuid":"obUGrpct6_5glrm7PNszgTLMtR32pIBSuXPrMkHGB-yO1DvTAsuRHaWtZtJjpIyNYd6a3wU2L_2f7Q",
        "gameName":"MATTyx",
        "tagLine":"m4gic",
        "leaderboardRank":30,
        "rankedRating":792,
        "numberOfWins":62,
        "competitiveTier":24
     },
     {
        "puuid":"IaaYZHp6ECT7WMvHOeKUY-6Cct8Zu-LHnZ_xRPD3Uw5qvthBibZ0xnQ4Uv7-Pf3hx63YbOLtSQL4rw",
        "gameName":"LKSHOW",
        "tagLine":"6924",
        "leaderboardRank":31,
        "rankedRating":790,
        "numberOfWins":54,
        "competitiveTier":24
     },
     {
        "puuid":"0N_RhNgnqd91ZIpqCBnZcNS0eJGkjQX1Xf2qpQcJVQAPrfEno9C_T8nsRsVcLq0lPCt9fe0odqCaYQ",
        "gameName":"w0ddy",
        "tagLine":"msz",
        "leaderboardRank":32,
        "rankedRating":788,
        "numberOfWins":93,
        "competitiveTier":24
     },
     {
        "leaderboardRank":33,
        "rankedRating":784,
        "numberOfWins":197,
        "competitiveTier":24
     },
     {
        "puuid":"N6OU0_awxqyXOnuiwuYHN0DPFHnaM-K0n4AemxfposJwtQ1imYrjdhV0Ymb-MSvNPnFf5jjn6i3fMQ",
        "gameName":"Ant",
        "tagLine":"sagim",
        "leaderboardRank":34,
        "rankedRating":783,
        "numberOfWins":74,
        "competitiveTier":24
     },
     {
        "puuid":"TstziX-st-Z8D-0k8uuZI3YJZelAiudszacL8WCHN3QZQzZ1r3mEM8ub_TqCegW4OpTsRbI07G0s9g",
        "gameName":"ind",
        "tagLine":"2003",
        "leaderboardRank":35,
        "rankedRating":780,
        "numberOfWins":96,
        "competitiveTier":24
     },
     {
        "puuid":"6DEK5fzYdd3-K6n1wJJ5wdWA0mougDb89kUWuMGNV8cRW7IvYl89IZ4z9FRwdGUoQvUAYb5GBZwckQ",
        "gameName":"FUR QCK",
        "tagLine":"000",
        "leaderboardRank":36,
        "rankedRating":773,
        "numberOfWins":67,
        "competitiveTier":24
     },
     {
        "puuid":"ApFStbHnJHQ1td-hjM02vc_J85XkXxzo2lM_YqO2jg4a3K3eAeV_MQfrR9R4D5pzfoCP4VHoCIieDw",
        "gameName":"forbanz",
        "tagLine":"PATEK",
        "leaderboardRank":37,
        "rankedRating":771,
        "numberOfWins":55,
        "competitiveTier":24
     },
     {
        "puuid":"qgeW3f-fTS9QyCopUxlCNmSs1MsyULh7KQQ18nrIVSExT3e-rLiwT9TnB_49KVx9fqEmfAoCEkeBrA",
        "gameName":"tisora",
        "tagLine":"zzz",
        "leaderboardRank":38,
        "rankedRating":752,
        "numberOfWins":94,
        "competitiveTier":24
     },
     {
        "puuid":"MqzJ3VYsdIi31YcwD3JCvNC7QZMpQ-Y0nugmXg3cDITLcFeXQDmadKYuiTqAptpvj4rZVSxcVf6sVQ",
        "gameName":"rmn",
        "tagLine":"7875",
        "leaderboardRank":39,
        "rankedRating":750,
        "numberOfWins":63,
        "competitiveTier":24
     },
     {
        "puuid":"JcLl7ndpkqRU1e9K5VVceuJczNJYGoEjh-UZ6u9kQbAFveTchPrHOD7uGR8Ti61JOfeURHYWxf-AAQ",
        "gameName":"tzin",
        "tagLine":"zin",
        "leaderboardRank":40,
        "rankedRating":748,
        "numberOfWins":94,
        "competitiveTier":24
     },
     {
        "puuid":"yPP2nfuH4PXsq6kYxDUzKcmmm1mnMV5NxcilvoGVXa5GBj97ZnQ9zNeDf8vWapkqpCu4twUqWmVLxA",
        "gameName":"MIBR teddxJESUS",
        "tagLine":"ssz",
        "leaderboardRank":41,
        "rankedRating":747,
        "numberOfWins":60,
        "competitiveTier":24
     },
     {
        "puuid":"FoPODMo_XLIvnOudmf6i07P1JveRx76fCtV3qMTAo459E-uYaXAkCtjjeeMfBJdgAnPOx5hA9wOymA",
        "gameName":"spec maluco",
        "tagLine":"limpo",
        "leaderboardRank":42,
        "rankedRating":744,
        "numberOfWins":74,
        "competitiveTier":24
     },
     {
        "puuid":"VUzCK6e8PiG2AxyjW5YkJPiB9UV5RWa44SeE58us64DauVkuuAtEGVPkEs8FgBuEQ_xCCEx9Llgfvw",
        "gameName":"feveTz",
        "tagLine":"fexY",
        "leaderboardRank":43,
        "rankedRating":733,
        "numberOfWins":105,
        "competitiveTier":24
     },
     {
        "puuid":"DJWN08D9NnYGF9sjBF0PpK2kYoyA3F1CD8rxbMcLqbbKWDPOsnccfMBDgZ6iOwPglKE2ZN83M4o-Iw",
        "gameName":"ntk",
        "tagLine":"1994",
        "leaderboardRank":44,
        "rankedRating":728,
        "numberOfWins":46,
        "competitiveTier":24
     },
     {
        "puuid":"bPTxWfWzGYL1pK5tRVezi5Nv85bMQhJfFk0cYms3P7wXIeANpu_mhkPsRy2BPrIMjOqeNljmyntbBg",
        "gameName":"jaozy",
        "tagLine":"2003",
        "leaderboardRank":45,
        "rankedRating":725,
        "numberOfWins":49,
        "competitiveTier":24
     },
     {
        "puuid":"LqY8BfBx0K_nQLRBdxqz1W2GoTrbFk9mED-u0c2dvmqidVt56-2Ywdp6iinyu6vUXXGOkvxj9CkG1g",
        "gameName":"rhazi",
        "tagLine":"wwwww",
        "leaderboardRank":46,
        "rankedRating":725,
        "numberOfWins":62,
        "competitiveTier":24
     },
     {
        "puuid":"RoBp43ejExwtCTybS6xldr1aXXq-_nu5-03V7Ad9cThFNuwKxtgpwxOD6A9ZHe5My_DtEce_SO_DLA",
        "gameName":"Xezaxi",
        "tagLine":"BAHIA",
        "leaderboardRank":47,
        "rankedRating":723,
        "numberOfWins":103,
        "competitiveTier":24
     },
     {
        "puuid":"q4dkeiiSkrVYLoNCoAam-XoLIJloMp2nTYzHvW3nuLQ5MoVZ7WlUphCEgBP1zIPZfAreoI7EpV7Mog",
        "gameName":"tooug",
        "tagLine":"zera",
        "leaderboardRank":48,
        "rankedRating":722,
        "numberOfWins":133,
        "competitiveTier":24
     },
     {
        "puuid":"aWZT3dO4sSkRttEfRad-GCiANH4Xqq-5d3cxBccfLo-hYGHGyevfcK8GTdB58afKgwSWqZtHw94m5w",
        "gameName":"xkz",
        "tagLine":"let",
        "leaderboardRank":49,
        "rankedRating":720,
        "numberOfWins":77,
        "competitiveTier":24
     },
     {
        "puuid":"kS9rbQdRLMQk1yF4tboNKK9IMmfdmQ99Qo-nTbpLsDC4nw7Jy2ey-tDopoyQDxnDYWV6cL07-6nl2w",
        "gameName":"TBK bizerra",
        "tagLine":"dom",
        "leaderboardRank":50,
        "rankedRating":720,
        "numberOfWins":85,
        "competitiveTier":24
     },
     {
        "puuid":"xEpNEHwRyVmz7xQ1gqHCGObcjNA9p4XmmWdj7hSdhXhItsmiv9fbqvHtcxq9w2uPSe8BwH397A4rkg",
        "gameName":"tinchoff",
        "tagLine":"BRA1",
        "leaderboardRank":51,
        "rankedRating":714,
        "numberOfWins":58,
        "competitiveTier":24
     },
     {
        "puuid":"z8PVLChL5O4HFFMI9AIcmVqLnk1kgwpzZiWTP97ievydpMG2bhkbm4ieePtKj2zS7A6SwwbP1vL1_Q",
        "gameName":"ShutAsY",
        "tagLine":"8070",
        "leaderboardRank":52,
        "rankedRating":714,
        "numberOfWins":102,
        "competitiveTier":24
     },
     {
        "puuid":"0iQ9Xuyx170YOBQ2aXAwckJWPg9V6ApOucm95JAeaaWUHtfy9XOKZVIa4tWoeXdO5Jz35BdC4KK-ZA",
        "gameName":"ODK axeddy",
        "tagLine":"maki",
        "leaderboardRank":53,
        "rankedRating":703,
        "numberOfWins":55,
        "competitiveTier":24
     },
     {
        "puuid":"OANKoFysscvOCd-kfixWCikReV_cEgwfVlaf6UApuYZu5tP_WXeUrd2uqm51jBrGEzTCtjcJAlHEuQ",
        "gameName":"PryZee",
        "tagLine":"budy",
        "leaderboardRank":54,
        "rankedRating":696,
        "numberOfWins":66,
        "competitiveTier":24
     },
     {
        "puuid":"33IRVqJVP5S4cIXFZnCo56EhcQkq4EtBJDDYuBYNTrzjX6fjo5FbsB0s47DIqrlo77WPK_zeiakPag",
        "gameName":"jnt",
        "tagLine":"jnt",
        "leaderboardRank":55,
        "rankedRating":694,
        "numberOfWins":69,
        "competitiveTier":24
     },
     {
        "puuid":"UsdAGkVN--1elg6Xdhk-8mqtDpWI5EdDG7DPCZxtjh7RY5YfVsielTz2HgACfGR43Dz784Ld4na3ig",
        "gameName":"Evilkyk",
        "tagLine":"fps",
        "leaderboardRank":56,
        "rankedRating":690,
        "numberOfWins":85,
        "competitiveTier":24
     },
     {
        "puuid":"Ppw8l4bgdFvQpDpQ4Qic9FAptGsAoKVhUVwM0lSXNYfeXxJtbVeRDqRMmaKAllNRr32fdn39HcjYNQ",
        "gameName":"TBK kon4n",
        "tagLine":"DTJ",
        "leaderboardRank":57,
        "rankedRating":690,
        "numberOfWins":64,
        "competitiveTier":24
     },
     {
        "puuid":"lQEvSNHLg_exz4c0yyrfMyk2zZWa0teLs3QwT188Jj60cVy1acfYtsBuMUaFAEZRkLTcw2SuYnxSGA",
        "gameName":"szk1",
        "tagLine":"2000",
        "leaderboardRank":58,
        "rankedRating":689,
        "numberOfWins":78,
        "competitiveTier":24
     },
     {
        "puuid":"luooBP8vN7eaip-kA1rAo9KFYTBmpGgfQQIA8sMCGorzcaKR9y86VB0fsTdDT97WzIlwBts6I0Xtew",
        "gameName":"Vengeance",
        "tagLine":"Ayla",
        "leaderboardRank":59,
        "rankedRating":687,
        "numberOfWins":166,
        "competitiveTier":24
     },
     {
        "puuid":"uZImZ01FsYXP4BjwHggQ9IMyGWmv_mSZW0E3f62li5wgHSqh44ARkyaqse52oQTQ28t3D9LL9wTknw",
        "gameName":"SHK Addicted",
        "tagLine":"1629",
        "leaderboardRank":60,
        "rankedRating":681,
        "numberOfWins":34,
        "competitiveTier":24
     },
     {
        "puuid":"w5ZFEqMMg_Ns4jgQmcxRDWedZ0IwCoreJcDGPDJ_UkU5W4QIcqZmd6dmcdsavbAYDk2QJ07ZRYt-RQ",
        "gameName":"FATAL",
        "tagLine":"XTUDO",
        "leaderboardRank":61,
        "rankedRating":681,
        "numberOfWins":80,
        "competitiveTier":24
     },
     {
        "puuid":"K00zroqosgfW3nw__JKqPmYbKEr8nauORbsh8wTKvjaZyZJiXzeauP67SB094CFMHRgao7iYVQfYBw",
        "gameName":"raafa",
        "tagLine":"ACE",
        "leaderboardRank":62,
        "rankedRating":679,
        "numberOfWins":63,
        "competitiveTier":24
     },
     {
        "puuid":"CZLQrgM9cuZZojnizXOw2XcYgvExCiasT52suesYKhRfbDEISH-wt0MCEgb3vsOLKePdCXVOvdWgEg",
        "gameName":"Lz ツ",
        "tagLine":"campo",
        "leaderboardRank":63,
        "rankedRating":677,
        "numberOfWins":90,
        "competitiveTier":24
     },
     {
        "puuid":"6FyA8KOyWBi_E_cLE109ZS9NHxiTOKRsxQl2bDg2KOY6bRAbkp-cpfBL6MkDXfFBuvQO_PyimjHcfg",
        "gameName":"eNOK",
        "tagLine":"IGL",
        "leaderboardRank":64,
        "rankedRating":673,
        "numberOfWins":64,
        "competitiveTier":24
     },
     {
        "puuid":"Hip980VLALmzNtuih_idPV35U8WBfQq_DKLqYy9e4dHYmyDMMls5ejsOGo1QzlNTkpp2FsJdF0t8Jg",
        "gameName":"francez1k",
        "tagLine":"god",
        "leaderboardRank":65,
        "rankedRating":671,
        "numberOfWins":65,
        "competitiveTier":24
     },
     {
        "puuid":"_fGlItsN_0spaeJBgeWBPMxF57rAd-DvSvN7Yv8wGgHcJzZRB7AN6CA8gGDT2Xq6otVBjITZJUETSw",
        "gameName":"Gabriel Infiel",
        "tagLine":"Sida",
        "leaderboardRank":66,
        "rankedRating":671,
        "numberOfWins":95,
        "competitiveTier":24
     },
     {
        "puuid":"6xAdSbCzHz1ttKc9Ipxhv25vOuayIZ90L83mZj8Bi9b1_8pfL221aR4G-TN0p6Chdkstcpjnv3-gcQ",
        "gameName":"Antunes",
        "tagLine":"gozei",
        "leaderboardRank":67,
        "rankedRating":671,
        "numberOfWins":103,
        "competitiveTier":24
     },
     {
        "puuid":"AaeD0cnYyi5OkwRN6rIgrTYbpNPwZd8LCR-rHDX4IW7KDzCTt11ln7d4Q1fW3s7HTygsBi5UdXsWpw",
        "gameName":"VKS polliNxL699",
        "tagLine":"vzdbk",
        "leaderboardRank":68,
        "rankedRating":670,
        "numberOfWins":38,
        "competitiveTier":24
     },
     {
        "puuid":"uuDhJEHzAhcY5hUkH5lFj3ogk21b3OECv5Zmiow2jTaV9c6PereKHsP969m8QO-ALRly6FQTv05h7Q",
        "gameName":"ODK silentzz",
        "tagLine":"be8",
        "leaderboardRank":69,
        "rankedRating":670,
        "numberOfWins":79,
        "competitiveTier":24
     },
     {
        "puuid":"6I90DYjcUSDhZLKdb_1x2S_JMcM4ik8GVpNbppEWMHgGLgkjU9ysw9rnL_Y3pvE6xBeGhzCyN0Jw6w",
        "gameName":"sekai",
        "tagLine":"1949",
        "leaderboardRank":70,
        "rankedRating":668,
        "numberOfWins":144,
        "competitiveTier":24
     },
     {
        "puuid":"ebffV9srz7bpTHm-F118-d9Fq5wKwWdAcsWqjlOidPs4iKvl_gEv0noFvvfuY6lLod970WYuDvr9ig",
        "gameName":"lucaoAV",
        "tagLine":"047",
        "leaderboardRank":71,
        "rankedRating":666,
        "numberOfWins":77,
        "competitiveTier":24
     },
     {
        "puuid":"DP3_8h5v5hjEjIJzCL0jE1Z_bGk8OlvEKXrRoAZo-ZUYNAmXVk_MLqXbVDDn0mGIm_-F_IeOgGwAlg",
        "gameName":"LOUD pANcada",
        "tagLine":"bryan",
        "leaderboardRank":72,
        "rankedRating":664,
        "numberOfWins":50,
        "competitiveTier":24
     },
     {
        "puuid":"GXPs0Y-MIxS8Bick1Q9zcRWqeN_SW-ePS7UPsDqCnkCMyplUdlLSaI27Lul_c6Lm5CGnnXPAprHqLw",
        "gameName":"TBK ryotzz",
        "tagLine":"1812",
        "leaderboardRank":73,
        "rankedRating":664,
        "numberOfWins":51,
        "competitiveTier":24
     },
     {
        "puuid":"yHLJ_LiwFrybh2YWJbeWSZP4PTBWJOmMlqU6bsnforYGNRs8rjsOYHnHOVEAhe5uupCDjdCJanTXew",
        "gameName":"LeeoLoos",
        "tagLine":"the1",
        "leaderboardRank":74,
        "rankedRating":664,
        "numberOfWins":43,
        "competitiveTier":24
     },
     {
        "puuid":"kpaJ9IS56pSvT65qgQJ7lBeGByG2m6qJyNDlepjjLrIYvBnbyP-fMpSgMPkKND_Q47BqHjslJuLMAg",
        "gameName":"snowspampiunpiun",
        "tagLine":"5738",
        "leaderboardRank":75,
        "rankedRating":664,
        "numberOfWins":146,
        "competitiveTier":24
     },
     {
        "puuid":"QRId3Yhvw9aEL-GfRx6wNiWdpU6dFysLjGI0gFg5WcRiUaSfOHv4IhxBaD290fiwHfw7HqnZM3EKXw",
        "gameName":"Längtan Får Ving",
        "tagLine":"agony",
        "leaderboardRank":76,
        "rankedRating":664,
        "numberOfWins":106,
        "competitiveTier":24
     },
     {
        "puuid":"agI8thCMwGJ1DG67FLf4tuUaX6vnAEXfM6nXAArMsIt0cK8MnzgoPBE1HgydC7BBTeU7R09PBdIQCA",
        "gameName":"driize",
        "tagLine":"exe",
        "leaderboardRank":77,
        "rankedRating":660,
        "numberOfWins":46,
        "competitiveTier":24
     },
     {
        "puuid":"wr39l5hbtO7QdJWj5HMoI1b2VUzhaPWlXYFsnOKrBIQVWOwUoahJ38iSTu_Y85jQu0clW34xXdezUg",
        "gameName":"lugn",
        "tagLine":"1337",
        "leaderboardRank":78,
        "rankedRating":659,
        "numberOfWins":63,
        "competitiveTier":24
     },
     {
        "puuid":"1Yva-wR5Qg2d19MweZg4rykTsbnSzGvtpRVQLU9sDTojPd7O6QaiCtW_d3NLFJsjKRNguaLIY29rmA",
        "gameName":"light",
        "tagLine":"0703",
        "leaderboardRank":79,
        "rankedRating":658,
        "numberOfWins":43,
        "competitiveTier":24
     },
     {
        "puuid":"6L6n8KBzcYi5ph61EKBQs1BpAIgY79FQnA9LJG6g7xUydQz-giRW8u36Xd-paFmzF8JmqJNV-rXfeg",
        "gameName":"LovX",
        "tagLine":"0705",
        "leaderboardRank":80,
        "rankedRating":657,
        "numberOfWins":61,
        "competitiveTier":24
     },
     {
        "puuid":"GaB5AB2RDQclKdIdsjldLata-V48gy7YkBathvFFKaDeuiv8IXYF9Gl_mpCniw-HcomDrIc-c8H3qg",
        "gameName":"G U I",
        "tagLine":"miaS2",
        "leaderboardRank":81,
        "rankedRating":657,
        "numberOfWins":96,
        "competitiveTier":24
     },
     {
        "puuid":"miBGGTEEYWgGNHPJwa390GAZn14awJ5KcnZYQR07jzyOA7Y7jaGd3i_WanuumIH8spe43zyOhRA25A",
        "gameName":"MIBR gtnziN",
        "tagLine":"2801",
        "leaderboardRank":82,
        "rankedRating":655,
        "numberOfWins":50,
        "competitiveTier":24
     },
     {
        "puuid":"qBizZOWKkHRNFUmhmvYMoxN-r976ZsWoGQXv_ML3Hmz0n3l0V8Xtcls-PWH-5L0h1nn4YLuDHrL7Cw",
        "gameName":"SlothP",
        "tagLine":"BR1",
        "leaderboardRank":83,
        "rankedRating":654,
        "numberOfWins":72,
        "competitiveTier":24
     },
     {
        "puuid":"BrY6V21vw9eUmyaDhgAXQYW8EjgYR4MJYFB-_9AnmJkPUOqjf_oP8uOS9M_lBaWxOkP5BrkjBkDYbQ",
        "gameName":"igaum",
        "tagLine":"igaum",
        "leaderboardRank":84,
        "rankedRating":654,
        "numberOfWins":87,
        "competitiveTier":24
     },
     {
        "leaderboardRank":85,
        "rankedRating":648,
        "numberOfWins":51,
        "competitiveTier":24
     },
     {
        "puuid":"sCXBfK1WItbySP41Mlwjai1JzL_aTWnqkIiGz2JzIGQu98aELyyhtkyhjoCWjQm865QPp4otAMdNIQ",
        "gameName":"NTS synkzinhoo0",
        "tagLine":"xoxo",
        "leaderboardRank":86,
        "rankedRating":648,
        "numberOfWins":62,
        "competitiveTier":24
     },
     {
        "puuid":"lIJ9hMCa-2Si3YkgxeYjwTSNqwhbSFQzX0y7GjrGmuZIbkrjytghKLuehDNooDeANKOTXifTWryaVA",
        "gameName":"Lmszin",
        "tagLine":"NTJ",
        "leaderboardRank":87,
        "rankedRating":645,
        "numberOfWins":42,
        "competitiveTier":24
     },
     {
        "puuid":"laLv8E9jfoBamO5WfgylFpGcZDyS_f9lf2Sx9TOPYu2BZtMNYZI9DP30u3ri3ncyDkAoQiptNBlsDw",
        "gameName":"Shin 神",
        "tagLine":"9999",
        "leaderboardRank":88,
        "rankedRating":645,
        "numberOfWins":94,
        "competitiveTier":24
     },
     {
        "puuid":"SJ41NKznazZoOJBM7gjcIIicD4w9OsD0UHKKOuICKSpJstkDx73ROSwuMcmqAR6q2qns-w4dQAT0EA",
        "gameName":"ODK snw",
        "tagLine":"lissa",
        "leaderboardRank":89,
        "rankedRating":643,
        "numberOfWins":65,
        "competitiveTier":24
     },
     {
        "puuid":"4_oKMf4QURGP31CK1GWM-0gqd4oUgh-G41yscfybSrgAEGDjhIJKSTnUKQJ8zyKkA5uMow7NKQ0ZPw",
        "gameName":"HiiiK",
        "tagLine":"Fr1tz",
        "leaderboardRank":90,
        "rankedRating":642,
        "numberOfWins":75,
        "competitiveTier":24
     },
     {
        "puuid":"kPk_ya6vxhoDYbQ6qGdgz1OAPUBiAKv93IUYjW9DmU2ouRitJ8BVzf3Ne34ZWfFKewZpCCCvxsCv_w",
        "gameName":"kanove",
        "tagLine":"nhapz",
        "leaderboardRank":91,
        "rankedRating":641,
        "numberOfWins":55,
        "competitiveTier":24
     },
     {
        "puuid":"qpqOHH5Foo8lxDRZ1lV28e522t3lpLKnTLtAieGwa-EQK7L-fZOJmqTT6MsZyliJgFRIHAQnYkLoLw",
        "gameName":"Akxshi",
        "tagLine":"SSS",
        "leaderboardRank":92,
        "rankedRating":640,
        "numberOfWins":55,
        "competitiveTier":24
     },
     {
        "puuid":"ZJuf2XlFNiqh1KXv9mjgKXyBgmoViNUdr9GJvbnG6W3p_MqRiyScFKz8ZCvc2zobl4klKA2Dg8_gsw",
        "gameName":"TBS ask1",
        "tagLine":"kell",
        "leaderboardRank":93,
        "rankedRating":639,
        "numberOfWins":85,
        "competitiveTier":24
     },
     {
        "puuid":"EZ8Uymy6Gqc4PyfrxEpBI_nwyWsEcITVSD0FlOJKRdIiIVxzoDijRqVknQH_HDbug0vIADykMiH54w",
        "gameName":"SHK KILLDREAMST",
        "tagLine":"9525",
        "leaderboardRank":94,
        "rankedRating":639,
        "numberOfWins":51,
        "competitiveTier":24
     },
     {
        "puuid":"lNWjxs1O8NisYEF73hNGYqNON2YuXsl5KKQHre0sDLHBQsl5Z3ddHp3ZE71K8ufHxp6OyA6D1BjFOg",
        "gameName":"MgL",
        "tagLine":"TREM",
        "leaderboardRank":95,
        "rankedRating":639,
        "numberOfWins":104,
        "competitiveTier":24
     },
     {
        "puuid":"qEdXY6XlQM4K30-9e51IkbmuFvRtAbADf7fQPkBdDijCEsE6Csf9OpvKw615LA10eaKviKhjpliltw",
        "gameName":"far",
        "tagLine":"3004",
        "leaderboardRank":96,
        "rankedRating":639,
        "numberOfWins":61,
        "competitiveTier":24
     },
     {
        "leaderboardRank":97,
        "rankedRating":636,
        "numberOfWins":42,
        "competitiveTier":24
     },
     {
        "puuid":"iuUK7FTKq7F30OP1fmxrIfQ3daPSVq7T2VscPLvmMXsfGhBDYvoJrkun5JRrI7x1VPgUPQvvy-Py4w",
        "gameName":"UNNSTO",
        "tagLine":"odin",
        "leaderboardRank":98,
        "rankedRating":635,
        "numberOfWins":116,
        "competitiveTier":24
     },
     {
        "puuid":"VBhDdTRuYnlkvmG1aqqh7Yrpc150BEcvM0EgKS59nP_usOFQiuG6IOf-bQpYQ1FVkm-AbCsd7xgWnA",
        "gameName":"Rood",
        "tagLine":"420",
        "leaderboardRank":99,
        "rankedRating":632,
        "numberOfWins":51,
        "competitiveTier":24
     },
     {
        "puuid":"SanDJ1Cn7TC7vv95o6PtbtyOEe_jonezLSohAhXNUVv2jkM4fQYOV2s-JQbz5IZZymnKqr4H8740hQ",
        "gameName":"Zanatsu",
        "tagLine":"2002",
        "leaderboardRank":100,
        "rankedRating":632,
        "numberOfWins":78,
        "competitiveTier":24
     },
     {
        "puuid":"alFR7OuPJgNXYZYwy55Gyv0GXt5MNFsTU8VX2oSrm597d1Te-6uTuUPdGuSTVYh0WpSJHnUIM47vTg",
        "gameName":"GL DUHT",
        "tagLine":"x5rs",
        "leaderboardRank":101,
        "rankedRating":631,
        "numberOfWins":78,
        "competitiveTier":24
     },
     {
        "puuid":"FFnbaYM6QpS_wjkyrExK5Cp48dUVhEtc_VhMlS2LQTJsHUg2egwlDnpZQAmx79xOrFBzQqOzZdU1cg",
        "gameName":"zakkv",
        "tagLine":"PK1",
        "leaderboardRank":102,
        "rankedRating":627,
        "numberOfWins":59,
        "competitiveTier":24
     },
     {
        "puuid":"I2t3xtZRhms40rnybO3nFsTPha3F-79VKKpLUsRxzufwc90uHuzSwNJ-TJ4rPcIRLxUQXolb9DzwrQ",
        "gameName":"SH dragonite",
        "tagLine":"drg",
        "leaderboardRank":103,
        "rankedRating":624,
        "numberOfWins":36,
        "competitiveTier":24
     },
     {
        "puuid":"1pT7PKCx8jal-XTQ1hcB7zIRYrX0JIwAwE-GorO8-f17jOghMLdFfjDdFkXFf3mOQ5KOdhmDB9rbBg",
        "gameName":"SHK frz",
        "tagLine":"2000",
        "leaderboardRank":104,
        "rankedRating":624,
        "numberOfWins":36,
        "competitiveTier":24
     },
     {
        "puuid":"Qib_OeIL9A79xNdO9hsC8n29pKbAFregn_fomodtnem-UARUVgI504o7EPlWSaGhBcC_BhWBI2S7Jg",
        "gameName":"ceron creator",
        "tagLine":"1923",
        "leaderboardRank":105,
        "rankedRating":624,
        "numberOfWins":70,
        "competitiveTier":24
     },
     {
        "leaderboardRank":106,
        "rankedRating":621,
        "numberOfWins":70,
        "competitiveTier":24
     },
     {
        "puuid":"ttyc-9sfvbmNbBaKCQf6_L2lSgV706GL8LkmNQxV0scK8nXD3nncSr0u0JouMhBZsiZgH7caxn35ig",
        "gameName":"magikerN",
        "tagLine":"tak",
        "leaderboardRank":107,
        "rankedRating":620,
        "numberOfWins":34,
        "competitiveTier":24
     },
     {
        "puuid":"eKYRHK5P06QvZVu0-jgLFQEQ2PFokANSGi4MUCrdvnA_kNR9y_TdEsP9Nvsq_L1nK7iEvDB_wr8BFQ",
        "gameName":"havoc",
        "tagLine":"2006",
        "leaderboardRank":108,
        "rankedRating":620,
        "numberOfWins":67,
        "competitiveTier":24
     },
     {
        "puuid":"ebyEm60cftqOZxedODe88uOLI9Pr9rP0vNZCPdox2b0vPWYV89CH-NM2ioatVCsuuUy6k7CROY5ifQ",
        "gameName":"TwitchDannyJones",
        "tagLine":"FORTE",
        "leaderboardRank":109,
        "rankedRating":619,
        "numberOfWins":92,
        "competitiveTier":24
     },
     {
        "puuid":"0ieh6iaiVgMLEwSIk5X9yyO-lIf3tbL_k8aOuh-pR4ajaVVD1LbrbOEsLThLEZz9OpbpsMIQmNBhzQ",
        "gameName":"TWITCH TCK10",
        "tagLine":"BICEP",
        "leaderboardRank":110,
        "rankedRating":619,
        "numberOfWins":163,
        "competitiveTier":24
     },
     {
        "puuid":"ZvEGtwKLC5xmZqSz-AMF1CzEeoq0mnABnN_i8HEqfL5ZIJAc5rkQJZiRSEvng4TgLreI8oYjAz9URg",
        "gameName":"OROCHI",
        "tagLine":"171",
        "leaderboardRank":111,
        "rankedRating":618,
        "numberOfWins":88,
        "competitiveTier":24
     },
     {
        "puuid":"j555oevkTip4oNZWMndz34HjMRwRPjJQ_YrE-1__6Vk_or2wuYG4DnemvxSsN_KjMhtTN3c1Zl17sA",
        "gameName":"stronda",
        "tagLine":"FMCKV",
        "leaderboardRank":112,
        "rankedRating":617,
        "numberOfWins":126,
        "competitiveTier":24
     },
     {
        "puuid":"KORr9YThcvsBsGGI4yoPfV_Yf0ZaBCw2v-DTxb7EB-fifniIMNarZUwqAMHET8vnRRK3J3KaE7I4Sg",
        "gameName":"NIP bnjaeger",
        "tagLine":"ninja",
        "leaderboardRank":113,
        "rankedRating":616,
        "numberOfWins":42,
        "competitiveTier":24
     },
     {
        "puuid":"Nm6OIpA97fMONIQFdcDm7RxYQUAOHvlsrciuoKzHxx9H8izHUklgMAQyLDklFGKVXvezJGdPvbMACg",
        "gameName":"mcn",
        "tagLine":"2old",
        "leaderboardRank":114,
        "rankedRating":616,
        "numberOfWins":63,
        "competitiveTier":24
     },
     {
        "leaderboardRank":115,
        "rankedRating":615,
        "numberOfWins":46,
        "competitiveTier":24
     },
     {
        "puuid":"wHvL0M669Yqs2pkhNePIgk4YvINRwllNMDMkuNQKx8oxpdLol6oHL4Zb4rptVsvPtEItYXMlLnHcHw",
        "gameName":"ING nanzin",
        "tagLine":"1994",
        "leaderboardRank":116,
        "rankedRating":614,
        "numberOfWins":48,
        "competitiveTier":24
     },
     {
        "puuid":"zHKhb2f5Asd_gOHM9noNm6Rq4zIiVOMttQiFLwWDAj9Ung3pjdus_2e4nYCHMw6I4OEV4lyejrkpXg",
        "gameName":"mdg virgulado",
        "tagLine":"212",
        "leaderboardRank":117,
        "rankedRating":614,
        "numberOfWins":78,
        "competitiveTier":24
     },
     {
        "puuid":"LJOa81vtCA6HH6GhPf3Pp_St26Nfewb2uhtEIw8IOxfOs93Km3rsq7dbxAJt3PZX7wsnUuIJ0Q84Eg",
        "gameName":"MDL Surpr1seee",
        "tagLine":"LEGND",
        "leaderboardRank":118,
        "rankedRating":613,
        "numberOfWins":40,
        "competitiveTier":24
     },
     {
        "puuid":"ReKOPKm5to3_6I-jmuDJYKWWDFV-I5BN3LmMFIPocFgRd_ziJ1MGjUl7e5pdiuJwpXl5LK9eaDXMOA",
        "gameName":"marcao 7tela",
        "tagLine":"iwnl",
        "leaderboardRank":119,
        "rankedRating":613,
        "numberOfWins":88,
        "competitiveTier":24
     },
     {
        "puuid":"J2_7lhft_UonMJ24dBMRX_7o85GDo40UyPTkUcomSWLsp_jR2tLmrZQaDQ_inRDfxBEijQKpb29C2w",
        "gameName":"GBzin",
        "tagLine":"dream",
        "leaderboardRank":120,
        "rankedRating":613,
        "numberOfWins":117,
        "competitiveTier":24
     },
     {
        "puuid":"TQPs3-fMXl_Zed26qMzxmGINhIAl3A26dJX2J9lczPOZX5_xHlhXLqx34QlNy-0DTOMUDnXdDQA3fg",
        "gameName":"Sttlolo",
        "tagLine":"ana",
        "leaderboardRank":121,
        "rankedRating":612,
        "numberOfWins":51,
        "competitiveTier":24
     },
     {
        "leaderboardRank":122,
        "rankedRating":612,
        "numberOfWins":117,
        "competitiveTier":24
     },
     {
        "puuid":"iUj_KB5zQQL0yrmuqpWFz3KVyV6z4JGNxUcEPDQUWR3PH6m9xKth46Axx9fCNIU_KhK1cMOZWGRwsw",
        "gameName":"gui",
        "tagLine":"2007",
        "leaderboardRank":123,
        "rankedRating":612,
        "numberOfWins":130,
        "competitiveTier":24
     },
     {
        "puuid":"Wum9msRsWTD4XXBB1zL2vZRDKE8aXdWFW0YN4bxlA_MoZN0WyonC0YQxMG9r7tn5kbIxwhSp4sN0HQ",
        "gameName":"VA JpL",
        "tagLine":"17y",
        "leaderboardRank":124,
        "rankedRating":612,
        "numberOfWins":93,
        "competitiveTier":24
     },
     {
        "puuid":"s5H6PfhMMTX-I4WtyViZHsESQJpPI11wdpCKa4Syh78WUfiLi6KVoZ7pKcb5bA-6CWdaNKdRfDUhFA",
        "gameName":"TWITCH LGAFPSS",
        "tagLine":"god",
        "leaderboardRank":125,
        "rankedRating":610,
        "numberOfWins":93,
        "competitiveTier":24
     },
     {
        "puuid":"wh1Y4VIVb4_lNqrEr-YGlxV5oe9KXLROF-Shp2YfnTfDdBylUhJtMx-IV1KAAey-sfziHR4QgOD47A",
        "gameName":"archy",
        "tagLine":"1337",
        "leaderboardRank":126,
        "rankedRating":606,
        "numberOfWins":114,
        "competitiveTier":24
     },
     {
        "puuid":"_qfK72bAujOPxKpdmYcsO1DsxE6puSE-GC3RhTkMl-djRVNyTnSk9O5LqaCx5kvWixbsIjokFB-iFg",
        "gameName":"senun",
        "tagLine":"cecy",
        "leaderboardRank":127,
        "rankedRating":605,
        "numberOfWins":133,
        "competitiveTier":24
     },
     {
        "puuid":"8FU5ozT5wX8FF6aKMaVz9nh2YYWfkRwhB9qefgQS0ws-ImV4dTmtaZso-6YLK0s9q5D60gsswSxjAA",
        "gameName":"NIP bezn1",
        "tagLine":"Ninja",
        "leaderboardRank":128,
        "rankedRating":604,
        "numberOfWins":31,
        "competitiveTier":24
     },
     {
        "puuid":"IwZ5mozvCL-V6Mch8V4NCT-wm2l74nr1uWyOT5M3ZfPNMYeM_CTXFwhTGROtZkg-4_xpxUWaMxRLAA",
        "gameName":"jayp",
        "tagLine":"2004",
        "leaderboardRank":129,
        "rankedRating":604,
        "numberOfWins":61,
        "competitiveTier":24
     },
     {
        "puuid":"tHDIkCalPupjfxWKC2_ZKocTRgKgF9ZjJsI4pjVvFfA5s98P80-OYam4p3ziJly2Zb8le_1U5qtjOw",
        "gameName":"unsainted japo",
        "tagLine":"mandy",
        "leaderboardRank":130,
        "rankedRating":603,
        "numberOfWins":89,
        "competitiveTier":24
     },
     {
        "puuid":"NQfVy9l-NvuLad9QKq76WZd4Kmxe2YPaFGQ0jPyI15_JyhlSTLle5R7tBTlbroxQo3DvQbteAasKkw",
        "gameName":"crushkz sentinel",
        "tagLine":"isis2",
        "leaderboardRank":131,
        "rankedRating":602,
        "numberOfWins":99,
        "competitiveTier":24
     },
     {
        "puuid":"Y0VctVwToH3NxHGrUPO4tjLqpn98l0d5v-ZTjFKi5TukVzH11MzMYhMklZQuMU_JsY3fSQ9i_wrltg",
        "gameName":"IRLV nickszxz",
        "tagLine":"sauce",
        "leaderboardRank":132,
        "rankedRating":600,
        "numberOfWins":82,
        "competitiveTier":24
     },
     {
        "puuid":"VzSuiVTeTO7JITmexOgcBFNAhfxgsZvShnzVyBgOSZO_HcwiL_47s0HZ7SXt-yFBfV1c9LSQTTLsYw",
        "gameName":"Paradox",
        "tagLine":"Dz1",
        "leaderboardRank":133,
        "rankedRating":599,
        "numberOfWins":85,
        "competitiveTier":24
     },
     {
        "puuid":"e2J4PQxC41338a07jobmva0N4A9ZZMM1XpJ1ihVMCzYH3k7l1W13dLO_7uPMudUS-EDvmQSZJtiolA",
        "gameName":"LSW BladeZ",
        "tagLine":"pato",
        "leaderboardRank":134,
        "rankedRating":596,
        "numberOfWins":47,
        "competitiveTier":24
     },
     {
        "puuid":"5ryof3tAo8vKLY9CSNHvKLQ24qX-N1BCWRksAtdraQlWOppuzeMdpdY2YhThPEwg3wM-EFVVyvnqZg",
        "gameName":"rodrok1ng",
        "tagLine":"micdl",
        "leaderboardRank":135,
        "rankedRating":595,
        "numberOfWins":97,
        "competitiveTier":24
     },
     {
        "puuid":"PSlTNLe9SiAL5G9FdSJVIA5mAf9RHhtk8qUq_buhRHQkW5r4_E6vsTdBeO5r_RtVvJ9p6jEAoQLFjw",
        "gameName":"gTTO",
        "tagLine":"1973",
        "leaderboardRank":136,
        "rankedRating":595,
        "numberOfWins":84,
        "competitiveTier":24
     },
     {
        "puuid":"GPktHf1d-XlaP4yasG69gV3SvEhC1gEN6K3ljvhkMzgvop3aX2usRoK3XjP0CbmtNkqex04C57Ec6w",
        "gameName":"GjW",
        "tagLine":"1313",
        "leaderboardRank":137,
        "rankedRating":594,
        "numberOfWins":44,
        "competitiveTier":24
     },
     {
        "puuid":"Al8SQbyNN72F7r9_zk8Ih_ww3z8qKc7hf6jeuUtlIp1KcLH0w3nI5kAeW5yyGyBxoCL6aT0ttWg5cg",
        "gameName":"MatiS",
        "tagLine":"CHL",
        "leaderboardRank":138,
        "rankedRating":592,
        "numberOfWins":54,
        "competitiveTier":24
     },
     {
        "puuid":"nxiB5IA1fqOjKudvo6RVidM3eDbyzVuSU9vjXd34qR9FhgwZmJEpgHY9MIJEklRxphcpTiPJ1k9TKA",
        "gameName":"poti",
        "tagLine":"3003",
        "leaderboardRank":139,
        "rankedRating":591,
        "numberOfWins":91,
        "competitiveTier":24
     },
     {
        "puuid":"27PT-Ho1HBRbOmRrTxp5zORUyAfLEt6wFeV0JotqYsuXvkRE70GTsL5wZokrvAcrfTlm_fX_ipOKoA",
        "gameName":"TWITCH HELKII",
        "tagLine":"lhama",
        "leaderboardRank":140,
        "rankedRating":590,
        "numberOfWins":67,
        "competitiveTier":24
     },
     {
        "puuid":"ifrolg6n7y9pg-CbHaKsJCSwqNJvm2n5Q5aG_Ircl_8U8b0eQ9vw_g7Yuosqxv2BdYdlE2L-5xQmqQ",
        "gameName":"LOS gustt1nha",
        "tagLine":"1971",
        "leaderboardRank":141,
        "rankedRating":589,
        "numberOfWins":32,
        "competitiveTier":24
     },
     {
        "puuid":"ENUZzdNSCU80BNTmT4pp77v8NgrJfxc3dlIDKJwDZ538utQjJZBpcDGD4bGZ8dBLf92Oz9kP4Nq0Mw",
        "gameName":"wo xi huan awp",
        "tagLine":"faaa",
        "leaderboardRank":142,
        "rankedRating":589,
        "numberOfWins":49,
        "competitiveTier":24
     },
     {
        "puuid":"UkrDYg0HOu2kSzNtHAFTVzGrWmxBeBu3oeWApuZTmdW_NZIREXO5jNEnVNrnaXVH-HXBiQGjqThhdA",
        "gameName":"propszin",
        "tagLine":"MVP",
        "leaderboardRank":143,
        "rankedRating":588,
        "numberOfWins":57,
        "competitiveTier":24
     },
     {
        "puuid":"IDHTrJrKYbNazsbbhkwyPgetwrN8zA-FpYkScqd1nR4WyGw57Yyxl4BZkmqE1TFjG9Ii8xjkCeMP-Q",
        "gameName":"Fallsz",
        "tagLine":"3379",
        "leaderboardRank":144,
        "rankedRating":586,
        "numberOfWins":97,
        "competitiveTier":24
     },
     {
        "puuid":"8wnnZS1hPxprm05Ht6YRPJdDavooDKQkr4PdbUGcHtc05bLOZp8nLfFR0C-UVTqTw39JcQj-GfyCGQ",
        "gameName":"6ix9ine",
        "tagLine":"swag",
        "leaderboardRank":145,
        "rankedRating":582,
        "numberOfWins":37,
        "competitiveTier":24
     },
     {
        "puuid":"alRYwuVSOBkicnRzJiLQ64EjKOe5g6eb1vgY-iito5A0NT7IXmobJVmzIoNqHQu7qfty1vP5EWEDIA",
        "gameName":"callmediscovery",
        "tagLine":"710",
        "leaderboardRank":146,
        "rankedRating":582,
        "numberOfWins":61,
        "competitiveTier":24
     },
     {
        "puuid":"us4VPtuM211DQCx83DjdD58-rL0moFJVwuq_4VRhjhI7dCi08LJKm_B8Hr3_0iVMh9Ljsyi5FiwTjw",
        "gameName":"TBK anao sato",
        "tagLine":"roth",
        "leaderboardRank":147,
        "rankedRating":575,
        "numberOfWins":76,
        "competitiveTier":24
     },
     {
        "puuid":"VB9VQIdFZT7Pm239pcQR4bMjyOkm0ik3bB7WxcQW82LlWdGy-X__eNEKbbJBzRUJEFL2oOHDeGqFBg",
        "gameName":"kylo",
        "tagLine":"LFT",
        "leaderboardRank":148,
        "rankedRating":574,
        "numberOfWins":100,
        "competitiveTier":24
     },
     {
        "puuid":"88A50-Bk79kJqv6lCv_C7WAI96Xf9Kk-VORRVP1mqLGsfh6mLeqEkC4vL4Uk9Kq-rufFzSRj56DVbA",
        "gameName":"vitrix",
        "tagLine":"9923",
        "leaderboardRank":149,
        "rankedRating":572,
        "numberOfWins":29,
        "competitiveTier":24
     },
     {
        "puuid":"3yhQjV_7grqw0Gp5NUldsFxIRTAoSeRmVO9ED-n2t_RcC_6QjYbwV24fyLytEhvYU3yPR6tomvI7EQ",
        "gameName":"Mätweedy",
        "tagLine":"666",
        "leaderboardRank":150,
        "rankedRating":572,
        "numberOfWins":52,
        "competitiveTier":24
     },
     {
        "puuid":"PUayvjpnMhFEHLbQAxcIVgkBk8SWhn5pw7ObXDLoaPDjvopAbBUYb4PRAx4s8SdcBvr8t8sqMC7aVg",
        "gameName":"bitokkα",
        "tagLine":"MVP",
        "leaderboardRank":151,
        "rankedRating":570,
        "numberOfWins":74,
        "competitiveTier":24
     },
     {
        "puuid":"pp7S3AEUbp5lWISSQALbFuL88RnyPejqmLLixpYkAmsoKTrH1WqoNdzCE7ndfg-CXVqQAaxyzKr19w",
        "gameName":"aimblessed",
        "tagLine":"911",
        "leaderboardRank":152,
        "rankedRating":570,
        "numberOfWins":64,
        "competitiveTier":24
     },
     {
        "puuid":"xt4ayuku9LYxMT42SSAKLQ7FeBzK4WZwFyJXbGOPvTlPgM3sbkRzhb76NHmfA28VsXSWwr2K6vf3yA",
        "gameName":"ODK sutecas",
        "tagLine":"BAGDA",
        "leaderboardRank":153,
        "rankedRating":569,
        "numberOfWins":71,
        "competitiveTier":24
     },
     {
        "puuid":"LO6wvJFHC_I_FflbbXWcQARbVCiTFwFoLCM7v1baC28K0Dpw9jkLGMjk7ZqlUiOgTVxEoMbeM6A2fw",
        "gameName":"9z mizu",
        "tagLine":"2310",
        "leaderboardRank":154,
        "rankedRating":567,
        "numberOfWins":42,
        "competitiveTier":24
     },
     {
        "puuid":"j_WeLjv9Zqrrq06nnkzSoNUO0a8_7fyTw3mCRdvi4jNrR2RKxV0eeU3LMrSUyZrgP-33srY34mcrQQ",
        "gameName":"KIPERGOD",
        "tagLine":"LEITE",
        "leaderboardRank":155,
        "rankedRating":567,
        "numberOfWins":81,
        "competitiveTier":24
     },
     {
        "puuid":"9_hg_MG0ogW0AtneKOW9p5PvuTYDEi9lSjSyYxchXdhBQ7tnCAxACF7tftQ3WDXUCeyspICi_qo9Iw",
        "gameName":"freNzykk",
        "tagLine":"777",
        "leaderboardRank":156,
        "rankedRating":566,
        "numberOfWins":50,
        "competitiveTier":24
     },
     {
        "puuid":"X1S-h89_1UXdWlraj5rAL41Z-KSF6BaIPNTXfBcGU9MqqtBObEE-yXX5O-v8d695qPnhee3BXE9Fmw",
        "gameName":"FURIA BREEZE",
        "tagLine":"BR2",
        "leaderboardRank":157,
        "rankedRating":566,
        "numberOfWins":67,
        "competitiveTier":24
     },
     {
        "puuid":"kZGeJaNubep7FIdoKKRVtd-9g1i-8MpAgfOpbIPWMWZSQWTzpzDmZh2hPQvotGfH0j3V6LVpt-dtYg",
        "gameName":"TBK lukzera",
        "tagLine":"1998",
        "leaderboardRank":158,
        "rankedRating":565,
        "numberOfWins":57,
        "competitiveTier":24
     },
     {
        "puuid":"G0JqPD2hsZSJ0Bzccq0X4Ha4O_dQr8-E8-xtZGLsOmN1l-To8fMLV_wY-QVSJVuF2aZsDtVAEPSB2A",
        "gameName":"anao tkzin",
        "tagLine":"cria",
        "leaderboardRank":159,
        "rankedRating":565,
        "numberOfWins":61,
        "competitiveTier":24
     },
     {
        "puuid":"Qnu8iv-ck9O5GgbkcXi0EaAR6EOraB7nLZHLZy0BSJ6Wg798i5zWucINmieEpRL0jvk4Bk_m3sTeeQ",
        "gameName":"SmK1",
        "tagLine":"1705",
        "leaderboardRank":160,
        "rankedRating":564,
        "numberOfWins":49,
        "competitiveTier":24
     },
     {
        "puuid":"CUG3do9GBsd0oLJqagTsf901wxhD15JSsv100ovqR_xYbhd0QECrzxhP_BC6sP9qqqlOjpqPRZAxqA",
        "gameName":"dmt",
        "tagLine":"cmtj",
        "leaderboardRank":161,
        "rankedRating":563,
        "numberOfWins":37,
        "competitiveTier":24
     },
     {
        "puuid":"GMaSLjGDvxb_uSwRxERulv2IiVw8H8peoKrEVJculBuoymWQ0UEZL0o7Bu9DWkXkaAsmgC5-VnwJ5w",
        "gameName":"MIBR tteuw",
        "tagLine":"777",
        "leaderboardRank":162,
        "rankedRating":563,
        "numberOfWins":51,
        "competitiveTier":24
     },
     {
        "puuid":"GMwOOQ_AQZH5CVKXhrNBzgxKrvz8dJjmJEq9tthH7j9IIkAkiXnwuUvZOnVnNTrc1RhiCo7QBYq7lg",
        "gameName":"faintz",
        "tagLine":"5979",
        "leaderboardRank":163,
        "rankedRating":562,
        "numberOfWins":97,
        "competitiveTier":24
     },
     {
        "leaderboardRank":164,
        "rankedRating":560,
        "numberOfWins":38,
        "competitiveTier":24
     },
     {
        "puuid":"qN4RucXyO4_YBvaTd6cUrHJFLOdfVcuoM7sEFJEp18JOy95z_tbTfT19WSy5ReDE6UfvMaoUieghHQ",
        "gameName":"Palla",
        "tagLine":"cria",
        "leaderboardRank":165,
        "rankedRating":560,
        "numberOfWins":90,
        "competitiveTier":24
     },
     {
        "puuid":"RduqwUeiH-KWH1UffJkXXtmXeIpxAnk8PgAu5F9N-leQDpP5NnqqGQkxd2i2WYi2rFWpvzlebPIczA",
        "gameName":"BLD",
        "tagLine":"OTS",
        "leaderboardRank":166,
        "rankedRating":559,
        "numberOfWins":70,
        "competitiveTier":24
     },
     {
        "puuid":"NwKEKKoPJGgVKU6s9AC3viYTnF-nlL-1QT9Lv8IlOgre24V8tKJ-_XB0IcwAoyrLvwrRiq_6tGqbnQ",
        "gameName":"Horakawa",
        "tagLine":"30 01",
        "leaderboardRank":167,
        "rankedRating":558,
        "numberOfWins":46,
        "competitiveTier":24
     },
     {
        "puuid":"rKnahRWoTaSsYtGhqGXVXDNHJznYbEfE0for20KJaiPV4plNTo2zgVEropQ4G4i4xz332hjTsE3Dpg",
        "gameName":"HagonIV",
        "tagLine":"Bibis",
        "leaderboardRank":168,
        "rankedRating":557,
        "numberOfWins":44,
        "competitiveTier":24
     },
     {
        "puuid":"fviEc_MM30eQyNvkGeE1Bol1tbTtrnwXv3aSP1xzdq7EoTVDRX5PaO3Rgm5wv3We0kCa8QsHiq2Lvg",
        "gameName":"fooxWETNIKVTSKNI",
        "tagLine":"NTJ",
        "leaderboardRank":169,
        "rankedRating":557,
        "numberOfWins":87,
        "competitiveTier":24
     },
     {
        "puuid":"N184GTw3uqxxVE6xTFUdYgFjTLMcJrDJkkKxmKCVsP9y8Iqby6v3t1PGZiX9D1tJ5Q44GbbAiwu-zQ",
        "gameName":"leakk0",
        "tagLine":"dream",
        "leaderboardRank":170,
        "rankedRating":555,
        "numberOfWins":56,
        "competitiveTier":24
     },
     {
        "puuid":"KA0TOhDwdFVIeCtpWjuW0anj3Lugk6DZeK7TawGm-VoUQAV-AER94SY1Lcy_xrbNOUV4WOK7JP9bQA",
        "gameName":"muri",
        "tagLine":"1312",
        "leaderboardRank":171,
        "rankedRating":555,
        "numberOfWins":63,
        "competitiveTier":24
     },
     {
        "puuid":"riigGtDrHBgvR9q11VisOds6P15Z4j1mXfCJSLVeEF88rlWUB6TLmfhBJLWrR5T6DoFz9PbKmxltVg",
        "gameName":"Slaag Law",
        "tagLine":"viv",
        "leaderboardRank":172,
        "rankedRating":552,
        "numberOfWins":75,
        "competitiveTier":24
     },
     {
        "puuid":"k1IdzSczonxN5levXpDxdQ_T_ICS7TVUO1XedJmEVbSWZ2_H7y5f-ngJipy043MLDhbR5ADHjsg0IA",
        "gameName":"GL joojina",
        "tagLine":"xnn",
        "leaderboardRank":173,
        "rankedRating":551,
        "numberOfWins":79,
        "competitiveTier":24
     },
     {
        "puuid":"zlaBr8j8QdZgL6giuJF43LrCIZmOVPgiMA0rbNyOUOXB5wMtMJQvtE5oMlpamRxlMq_jAmcqIfQKlA",
        "gameName":"TBK matheuzinn",
        "tagLine":"0303",
        "leaderboardRank":174,
        "rankedRating":549,
        "numberOfWins":36,
        "competitiveTier":24
     },
     {
        "puuid":"GKoF7McoNvj7W32tgMo4INn0g8p2U1jIsCn94lSspqDB4qa6rN2d57SH8po53qYxRHf-nOBoCjJLfA",
        "gameName":"PKX",
        "tagLine":"OPIKA",
        "leaderboardRank":175,
        "rankedRating":549,
        "numberOfWins":39,
        "competitiveTier":24
     },
     {
        "puuid":"FCi9fDJLJJmq6lwnd-oPXUZYYzzdRBaaFWveaCV1lXJz8jmkcFKGkpdSK1hGm_tLxnP8-MGcP9sQtQ",
        "gameName":"Retroyd",
        "tagLine":"000",
        "leaderboardRank":176,
        "rankedRating":548,
        "numberOfWins":46,
        "competitiveTier":24
     },
     {
        "puuid":"66RBrXwYWxOhuxNCGpkhP7xDTWeG0DNQIDyhlBuZvG_pCr61TE0c_xpn9xENMemCUYbekQUYcfuCyg",
        "gameName":"Ecard",
        "tagLine":"1337",
        "leaderboardRank":177,
        "rankedRating":548,
        "numberOfWins":80,
        "competitiveTier":24
     },
     {
        "puuid":"aXjA_EOUSpd0xsZoEvAipmrrFPXPc1G9gKhRvD1_ghYThKdhZMRgkFjk_uO99U0Z3L6uZhpxzcXAaQ",
        "gameName":"GANGSTERDEGALPAO",
        "tagLine":"171",
        "leaderboardRank":178,
        "rankedRating":548,
        "numberOfWins":54,
        "competitiveTier":24
     },
     {
        "puuid":"EApveLF1qDWAnTa0ohd8_Pt_yQVhyovODtr7gj_lJNj21VYBhjw0nNsMieW4Ki827x487ulXCqhSaA",
        "gameName":"Maestr0 RarePeek",
        "tagLine":"17y",
        "leaderboardRank":179,
        "rankedRating":546,
        "numberOfWins":25,
        "competitiveTier":24
     },
     {
        "puuid":"uiuDpK85Y_ooO2lcO_5Y4A-QC7Kyjsj86J0ELp5o5B82TKoy4I-Gc0ZW7VEceIHtnq6lgirIxTtBJQ",
        "gameName":"LIBERTY liazzi",
        "tagLine":"yolo",
        "leaderboardRank":180,
        "rankedRating":546,
        "numberOfWins":29,
        "competitiveTier":24
     },
     {
        "puuid":"22F2YHT63aZSZT-wnw15bllSsFX4jZ3w9vfYUkNpjYmklQt0UMQW3DGPH38CHow9rhBx_IwIwPgeow",
        "gameName":"ING BRNWOWZK1",
        "tagLine":"ZK1",
        "leaderboardRank":181,
        "rankedRating":546,
        "numberOfWins":43,
        "competitiveTier":24
     },
     {
        "puuid":"0KZyl4PPMUtaFwrxyqbz7FjOQWd5khgDho1C0nv50UtDhzTLzG2e_s2AF8f8YLmqw6y8vGxSnnY7kA",
        "gameName":"Guiih9",
        "tagLine":"fsz",
        "leaderboardRank":182,
        "rankedRating":546,
        "numberOfWins":101,
        "competitiveTier":24
     },
     {
        "puuid":"Hh-I31hSK2mmAK8aeWjwlrbbv4dTWGK0gKOtzvQD6qqUzcBfDtu8yssRcpQ78axYEl-W-Ic0JnSsMQ",
        "gameName":"takeszin",
        "tagLine":"2000",
        "leaderboardRank":183,
        "rankedRating":546,
        "numberOfWins":73,
        "competitiveTier":24
     },
     {
        "puuid":"-O7U37WLToFL-dKUsZY7RYCz_0clCiUKLajTtidrij29Q6uC6RrYRTLZhLxgmzUgkfX3jUSzmsJpbQ",
        "gameName":"LHS Brood",
        "tagLine":"fps",
        "leaderboardRank":184,
        "rankedRating":545,
        "numberOfWins":29,
        "competitiveTier":24
     },
     {
        "puuid":"DQDeEEVpYHlSyR-cg1qhF6lSLNohjWYlZS36IitRNDdalcQNlX8oRASxk3HWM-wsSJGtglkuAF4oaA",
        "gameName":"LOS pleetsziN",
        "tagLine":"SCCP",
        "leaderboardRank":185,
        "rankedRating":544,
        "numberOfWins":36,
        "competitiveTier":24
     },
     {
        "puuid":"RPoAWUV9n3th9lpfcZbvk6SErOWfpr7PoSuh6n8UH2gUmV1DFspdKncEfczTXYw7aPYgbk5pOAeKiQ",
        "gameName":"RISE LUSKKÃO",
        "tagLine":"747",
        "leaderboardRank":186,
        "rankedRating":542,
        "numberOfWins":74,
        "competitiveTier":24
     },
     {
        "puuid":"PDFg0s-SNpWFiVyGFMxNcKg3haOWMW-fEpkePKEmAvboJC6YP6OezXBvnNNRqXtF3DAkbJSzMIuTtA",
        "gameName":"tintinns2",
        "tagLine":"s222",
        "leaderboardRank":187,
        "rankedRating":542,
        "numberOfWins":82,
        "competitiveTier":24
     },
     {
        "puuid":"_SDUh3XUQQH1G5vzPUpf21RmcxgJce9xqYusBRcKEmRhBEXJqW3tv-vgebGq_ULiUf5dov6V4gtd6Q",
        "gameName":"FA roxthi",
        "tagLine":"2712",
        "leaderboardRank":188,
        "rankedRating":541,
        "numberOfWins":124,
        "competitiveTier":24
     },
     {
        "puuid":"AOkOpNsGvJsODslEYbHhyLlIozi5gbXVk78rMfM9pEOFGZ4pdEoslXXhhEVL00iK44h2ELLYakRbeA",
        "gameName":"Nickz999",
        "tagLine":"6666",
        "leaderboardRank":189,
        "rankedRating":541,
        "numberOfWins":81,
        "competitiveTier":24
     },
     {
        "puuid":"_tt9SFR8bYwp5ppDMvN3rIA36xuvrpo5CxlbjpyC9TxWRtZTC_RYWkLAE2Itx3lK6_rX4cCpjwTEpQ",
        "gameName":"AMIGO DO GAGO",
        "tagLine":"GAGO",
        "leaderboardRank":190,
        "rankedRating":541,
        "numberOfWins":81,
        "competitiveTier":24
     },
     {
        "puuid":"5mh2gwL-5YgQGXgzQMBOLKeSStKrkP31dEvz6379ghNCo8wo_EKNPQ50Rl4bOW9RvgDamNkjmuYqjA",
        "gameName":"mxm",
        "tagLine":"fps",
        "leaderboardRank":191,
        "rankedRating":540,
        "numberOfWins":36,
        "competitiveTier":24
     },
     {
        "puuid":"1-j22SAlBd5oaVy-BZlbC2z3NTbLrobXCiRz6Bqk6LkzruxRXU8MWGsf_BX7WlJ8QSWDMazoEPzBpQ",
        "gameName":"Djjoka",
        "tagLine":"1107",
        "leaderboardRank":192,
        "rankedRating":540,
        "numberOfWins":56,
        "competitiveTier":24
     },
     {
        "puuid":"lXSfsWiEY7X0I4jOg86o54jVGnnkPrEnAJPOMD44117BFgHB6-zCP_5ukzFCCZWJHKm18Qak86O1kw",
        "gameName":"Brau má fase",
        "tagLine":"2001",
        "leaderboardRank":193,
        "rankedRating":540,
        "numberOfWins":84,
        "competitiveTier":24
     },
     {
        "puuid":"GCDH5YIt6XKIV8xgtxLAIH8tvz64rKjhqUdHzqM97YTNKf5QELzOQl1-LrP981n9KaQ6X6ij5NrI0Q",
        "gameName":"ORN Nyxx",
        "tagLine":"Boss",
        "leaderboardRank":194,
        "rankedRating":539,
        "numberOfWins":130,
        "competitiveTier":24
     },
     {
        "puuid":"qQ5ATTB5plkscCNqFNst7wTajOldkq5uuaFw7JGGXb7VKJ4HEAGbX75VUxs8Gl3D7n_ll80zQiE2Rw",
        "gameName":"DiMAS",
        "tagLine":"naosh",
        "leaderboardRank":195,
        "rankedRating":538,
        "numberOfWins":47,
        "competitiveTier":24
     },
     {
        "puuid":"FePjz_stkUW0pu3mDisjz6H-0PP9vRhGN9n1HJVI19jKCzYaiLNhui7Fb3ofFUwZrVei0Evu6pPCOg",
        "gameName":"火 BlazeK1nn 火",
        "tagLine":"021",
        "leaderboardRank":196,
        "rankedRating":538,
        "numberOfWins":99,
        "competitiveTier":24
     },
     {
        "puuid":"mAdWhGyohZ8hjHfOusSW7-U7UesKt6_ZMfkoe03ipW0A2yh8c0PB3mmcOFmuER8736XaShydoFNtdA",
        "gameName":"Beast",
        "tagLine":"only",
        "leaderboardRank":197,
        "rankedRating":536,
        "numberOfWins":64,
        "competitiveTier":24
     },
     {
        "puuid":"jaHqOHd2jMPR5Xx-wpm7p5fwhJ9BRhHQ_qx_mi5XK36RbNrsLIB-vMimbv1DUmPToVal6t4aPWSp7g",
        "gameName":"bleyw0w",
        "tagLine":"027ta",
        "leaderboardRank":198,
        "rankedRating":535,
        "numberOfWins":66,
        "competitiveTier":24
     },
     {
        "puuid":"I4flL2q4S_qVBcCaLmlseUGGdCPWoHwaIno832GcgvxnDk6sma4tfXWkb6Y7G16Zn0ffqoRV_LMvQg",
        "gameName":"high",
        "tagLine":"m23",
        "leaderboardRank":199,
        "rankedRating":533,
        "numberOfWins":77,
        "competitiveTier":24
     },
     {
        "puuid":"YXZBH5mrPdJToiBv6A5lAxB3GWmOSBq_uikadTYKSHg_BgpLRojHxXuPuBbq2Cb2fdP_QzkuDN2iow",
        "gameName":"ING flainzz",
        "tagLine":"1995",
        "leaderboardRank":200,
        "rankedRating":532,
        "numberOfWins":80,
        "competitiveTier":24
     }
  ],
  "totalPlayers":7135,
  "immortalStartingPage":3,
  "immortalStartingIndex":501,
  "topTierRRThreshold":340,
  "tierDetails":{
     "21":{
        "rankedRatingThreshold":0,
        "startingPage":17,
        "startingIndex":3206
     },
     "22":{
        "rankedRatingThreshold":100,
        "startingPage":7,
        "startingIndex":1275
     },
     "23":{
        "rankedRatingThreshold":230,
        "startingPage":3,
        "startingIndex":501
     },
     "24":{
        "rankedRatingThreshold":340,
        "startingPage":1,
        "startingIndex":1
     }
  },
  "startIndex":0,
  "query":"",
  "shard":"br"
}


filteredBoard= leaderBoard.players.map(x=>({
  rank:x.leaderboardRank,
  name:x.gameName??"ANONIMO",
  points:x.rankedRating,
}));
/* GET home page. */
router.get('/', function(req, res, next) {
  res.render('index', { title: 'Express', list:[[1,2],[3,4]] });
});
router.get('/val', function(req, res, next) {
  res.render('index', { title: 'VALORANT', list: filteredBoard});
});
/* GET home page. */
router.get('/data', async function(req, res, next) {
  var l = await valorant.getLeaderboard('d929bc38-4ab6-7da4-94f0-ee84f8ac141e');
  res.send(l)
});

module.exports = router;

